### ISSUE TITLE
BookMonkey does not work in Node 12

### ISSUE THREAD

**Issue by GregOnNet** [workshops-de/bookmonkey-api#8]
Problem

```
npx bookmonkey-api
npx: installed 218 in 8.585s
(node:49221) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/gregor/.npm/_npx/49221/lib/node_modules/bookmonkey-api/middlewares/shared.js:1
import { json, urlencoded } from 'express'
         ^^^^
SyntaxError: The requested module 'express' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'express';
const { json, urlencoded } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:136:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

Workaround

```
npx bookmonkey@3.0.4
```

**Comment by antony-k1208** [comment]
You should update your node version, since 12's end-of-life is coming soon: 2022-04-30 =)
Currently its in maintenance mode only. At least 14 should be used as new active LTS version

**Comment by GregOnNet** [comment]
This is not true for all of our customers being forced using older versions by IT-policy.

**Comment by GregOnNet** [comment]
We should publish bookmonkey@4 to make clear that we have a breaking change.

**Comment by antony-k1208** [comment]
True. Can you @GregOnNet check and test https://github.com/workshops-de/bookmonkey-api/pull/9 quickly? I've tested it with 12.16.1 and it worked, but it would be nice if you could cross-check.

Since we are only gaining something from a developer's point of view with the es modules, we should rather go back to the commonjs modules and re-enabling the usage of this package to all users again.

**Comment by GregOnNet** [comment]
looks good
